version: ''3''

networks:
  webnet:

services:
  redmine:
    image: redmine
    networks:
      webnet:
        aliases:
          - demo-redmine

  nginx-proxy:
    build: ./
    ports:
      - 443:443
    networks:
      - webnet
